account/urls.py
from django.contrib import admin
from django.urls import path, include

from account.views import *

app_name = 'account'

urlpatterns = [
    path('login/', CustomLoginView.as_view(), name="login"),
    path('register/', CustomRegisterView.as_view(), name="register"),
    path('log-out/', CustomLogOutView.as_view(), name="logout"),
    path('profil', Profil.as_view(), name="profil")
]
    

main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from main import settings

app_name = "main"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('memorize.urls')),
    path('', include('account.urls'))

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

memorize/urls.py
from django.contrib import admin
from django.urls import path, include

from memorize.views import *

app_name = 'memorize'

urlpatterns = [
    path('', CustomHomeView.as_view(), name="home"),
    path('checked/<int:pk>', taskChecked, name="checked"),
    path('create', addTask, name="create"),
    path('game-reminder/', reminderGameTask, name="reminder-game"),
    path('game-reminder-check/<pk>/', reminderGameTaskCheck, name="reminder-game-check"),
    path('game-food/', foodGameTask, name="food-game"),
    path('game-food-check/<int:pk>/<str:option>/', foodGameTaskCheck, name="food-game-check"),
    path('game-reset-reminder/', resetScoreReminder, name="reset-game-score-reminder"),
    path('game-reset-food/', resetScoreFood, name="reset-game-score-food"),
]

memorize/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.utils.text import slugify
from django.core.validators import RegexValidator
from account.models import CustomUser
from datetime import datetime
# Create your models here.

phoneNumberRegex = RegexValidator(regex = r"^\+?1?\d{8,15}$")   
User = get_user_model()

class Category(models.Model):
    title = models.CharField(max_length=255, blank=False, verbose_name="titre")
    color = models.CharField(max_length=255, blank=True, verbose_name="couleur")
    thumbnail = models.ImageField(max_length=255, blank=True, upload_to="categories")

    class Meta:
        verbose_name = "Catégorie"

    def __str__(self):
        return self.title

class Status(models.Model):
    title = models.CharField(max_length=255, blank=False, verbose_name="titre")
    slug = models.SlugField(max_length=255, blank=True, verbose_name="slug")

    class Meta:
        verbose_name = "Statu"
    
    def save(self, *args, **kwargs):
        if not self.slug :
           self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.title

class Task(models.Model):
    title = models.CharField(max_length=500, blank=False, verbose_name="Nouvelle tâche")
    subtitle = models.CharField(max_length=255, blank=True, verbose_name="Sous-titre")
    created_on = models.DateTimeField(auto_now_add=True)
    made_on = models.CharField(default="none", blank=True, max_length=255, verbose_name="date de réalisation")
    remind = models.BooleanField(default=False, blank=False)
    category = models.ForeignKey(Category, verbose_name="Catégories", on_delete=models.SET_NULL, null=True)
    status = models.ForeignKey(Status, verbose_name="status", on_delete=models.SET_NULL, null=True)
    user = models.ForeignKey(User, verbose_name="Utilisateur", on_delete=models.SET_NULL, null=True)

    class Meta:
        verbose_name = "Tache"

    def save(self, *args, **kwargs):
        self.title = self.title.capitalize()
        if not self.subtitle :
           self.subtitle = slugify(self.title)
        if not self.status : 
            self.status = Status.objects.get(pk=1)
        super().save(*args, **kwargs)
    
    def modify_status(self):
        if self.status.pk < 3 :
            self.status = Status.objects.get(pk = self.status.pk + 1)
            self.made_on = datetime.now().strftime("%d-%m-%y")
        self.save()

    def created_on_str(self):
        return self.created_on.date()

    def __str__(self):
        return self.title

class Contact(models.Model):
    firstname = models.CharField(max_length=255, blank=False)
    lastname = models.CharField(max_length=255, blank=False)
    email = models.EmailField(max_length=255, blank=False)
    phone = models.CharField(max_length=255, blank=False)

class FoodGame(models.Model):
    question = models.CharField(max_length=255, blank=False, verbose_name="Question")
    option = models.CharField(max_length=255, blank=False,default="none", verbose_name="Différentes options")
    answer = models.CharField(max_length=255, blank=False, verbose_name="Réponse")

    class Meta:
        verbose_name = 'Questionnaire sur les Menu'

    def __str__(self):
        return self.question[:50]

memorize/forms.py
from django import forms
from django.forms import MultiWidget
from django.forms.widgets import CheckboxSelectMultiple, NumberInput, SelectDateWidget, DateInput, DateTimeInput
from django.contrib.auth.forms import UserCreationForm
from memorize.models import Task, Category


import datetime
from django.core.validators import MinValueValidator, MaxValueValidator

categories = Category.objects.all()
CATEGORY = [(categorie.title, categorie.title) for categorie in categories]

class AddTaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ('category', 'title')
        widgets = {'category' : forms.RadioSelect(), 
                    'title' : forms.TextInput(attrs={'placeholder' : "Ecrivez le nom de votre tâche ici et Entrée..."})}

    

memorize/views.py
from django.shortcuts import render
from django.views.generic import View, TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView
from django.shortcuts import get_list_or_404, render, redirect, get_object_or_404
from django.urls.base import reverse_lazy, reverse
from django.http import HttpResponse, HttpResponseRedirect
from memorize.models import Task, Category, FoodGame
from memorize.forms import AddTaskForm
import datetime
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin


# Create your views here.

class CustomHomeView(TemplateView):
    template_name = 'memorize/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = "Bienvenu"
        if self.request.user.is_authenticated:
            context['tasks'] = Task.objects.filter(user = self.request.user).all()
        context['form'] = AddTaskForm()
        try :
            context['username'] = self.request.user.email.split('@')[0]
        except IndexError:
            context['username'] = self.request.user
        return context

@login_required
def taskChecked(request, pk):
    task = get_object_or_404(Task, pk=pk)
    task.modify_status()
    return redirect('memorize:home')

@login_required
def addTask(request):
    if request.method == 'POST':
        form = AddTaskForm(request.POST)
        form.instance.user = request.user
        form.save()
    return redirect('memorize:home')

@login_required
def reminderGameTask(request):
    test_ok = False
    count = 0
    while not test_ok:
        tasks = Task.objects.filter(user=request.user).exclude(status__pk = 3).order_by('?')[:3]
        count += 1
        for task in tasks:
            if task.made_on == datetime.datetime.now().strftime("%d-%m-%y"):
                test_ok = True
        if count == 3 :
            test_ok = True
                
    question = "Quelle activité avez-vous réalisés en aujourd'hui?"
    session = request.session
    win = session['win']
    tryied = session['tryied']
    title = "Reminder Game"
    return render(request, 'memorize/remind-game.html', context = {"tasks" : tasks, "question" : question, 'win':win, 
        'tryied' : tryied, 'title' : title})

@login_required
def reminderGameTaskCheck(request, pk):
    if request.method == 'GET':
        session = request.session
        task = get_object_or_404(Task, pk=pk)
        if task.made_on == datetime.datetime.now().strftime("%d-%m-%y") and task.status.pk > 1 :
            messages.success(request, "Bravo, C'est la bonne réponse.")
            session['win'] = 1 if session['win'] < 1 else session['win'] + 1
        else:
            messages.error(request, "Perdu, Ce n'était pas la bonne réponse.")
        session['tryied'] = 1 if session['tryied'] < 1 else session['tryied'] + 1
    return redirect('memorize:reminder-game')

@login_required
def foodGameTask(request):
    title = "Reminder Game"
    session = request.session
    win = session['win']
    tryied = session['tryied']
    question = FoodGame.objects.order_by('?')[0]
    options = question.option.split('.')
    return render(request, 'memorize/food-game.html', context = {'title' : title, 'win' : win, 'tryied' : tryied, 'question' : question, "options" : options})

@login_required
def foodGameTaskCheck(request, option, pk):
    if request.method == 'GET': 
        session = request.session
        answer = FoodGame.objects.get(pk=pk).answer
        if answer == option : 
            messages.success(request, "Bravo, C'est la bonne réponse.")
            session['win'] = 1 if session['win'] < 1 else session['win'] + 1
        else:
            messages.error(request, "Perdu, Ce n'était pas la bonne réponse.")
        session['tryied'] = 1 if session['tryied'] < 1 else session['tryied'] + 1
        return redirect('memorize:food-game')

@login_required
def resetScoreFood(request):
    if request.method == 'POST':
        request.session['win'] = 0
        request.session['tryied'] = 0
    return redirect('memorize:food-game')

@login_required
def resetScoreReminder(request):
    if request.method == 'POST':
        request.session['win'] = 0
        request.session['tryied'] = 0
    return redirect('memorize:reminder-game')

memorize/templates/memorize/_flash.html
{% if messages %}
<ul class="messages mt-3">
    {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

memorize/templates/memorize/_score.html
<section class="container text-center mt-3">
    <div class="score">
        <div>
            {% if tryied > 0 %}
                <h2 class="mb-3">Votre Score : <br> {{ win }} sur {{ tryied }} {% if tryied > 1 %} questions {% else %} question {% endif %}</h2>
                <form action="{% url 'memorize:reset-game-score-reminder' %}" method="post">
                    {% csrf_token %}
                    <input type="submit" value="Retour à zéro" class="btn">
                </form>
            {% else %}
                <h2>Répondez aux questions!</h2>
            {% endif %}
        </div>
    </div>
</section>

memorize/templates/memorize/base.html
{% load static %}
<!DOCTYPE html>
<html lang="fr-FR">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Memories - {% block title %}{% endblock %}</title>
    {% block css %}
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        <link href="{% static 'css/style.css' %}" rel="stylesheet">
    {% endblock %}
</head>
<body>
    <header>
        <nav>
            {% if user.is_authenticated %}
            <a href="{% url 'account:profil' %}">{{ user.first_name}}</a>
            {% endif %}
            <ul class="d-flex">
                {% if not user.is_authenticated %}
                <li><a class="" href="{% url 'account:login' %}">Se connecter</a></li>
                <li><a class="" href="{% url 'account:register' %}">Créer un compte</a></li>
                {% else %}
                <li><a href="{% url 'memorize:home' %}">Home</a></li>
                <li><a href="{% url 'memorize:home' %}">Profil</a></li>
                <li><a href="{% url 'memorize:reminder-game' %}">Reminder!</a></li>
                <li><a href="{% url 'memorize:food-game' %}">Food-Game</a></li>
                <li class="ms-auto"><a href="{% url 'account:logout' %}">Se déconnecter</a></li>
                {% endif %}
            </ul>
        </nav>
    </header>
    {% block content %}
        
    {% endblock %}
    <footer>
        <nav>
            Rajouter un footer
        </nav>
        <script src="{% static 'js/game.js' %}"></script>
        <script src="{% static 'js/flash.js' %}"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
        {% block footer %}{% endblock %}
    </footer>
</body>
</html>

memorize/templates/memorize/food-game.html
{% extends 'memorize/base.html' %}

{% block title %} Food Game {% endblock %}

{% block content %}
    {% include 'memorize/_flash.html' %}
    <section class="container game">
        <h1 class="text-center">{{ question }}</h1>
        <ul class="d-flex justify-content-center">
            {% for option in options %}
            <li class="m-2">
                <a class="btn btn-lg" href="{% url 'memorize:food-game-check' option=option pk=question.pk %}">
                    {{ option | title }}
                </a>
            </li>
            {% endfor %}
        </ul>    
        {% include 'memorize/_score.html' %}
    </section>  
    
{% endblock %}

memorize/templates/memorize/index.html
{% extends 'memorize/base.html' %}
{% load static %}

{% block title %} {{title}} {% endblock %}

{% block content %}
    {% if user.is_authenticated %}
        <section class="container">
            <h1 class="text-center m-3">{{ title }} {{ username | title }}</h1>  
            <p class="text-center"><em>Votre dernière connexion était le {{ user.last_login_str }}.</em></p>
            <section class="row flex-wrap justify-content-evenly align-item-start">
                <div class="col-12 col-lg-4 section-form-todo">
                    <h2 class="text-center mb-3">Ajouter une nouvelle tâche</h2>
                    <form action="{% url 'memorize:create' %}" method="post">
                        {% csrf_token %}
                        <table>
                            {{ form.as_p }}
                        </table>
                        <input id="submit" type="Submit" class="btn btn-lg" value="Ajouter une tache" hidden>
                    </form>
                    <div class="text-center w-50 m-auto">
                        <img src="{% static 'img/logo_rec.png' %}" alt="" class="resp">
                    </div>
                </div>
                <div class="col-12 col-lg-8">
                    <h2 class="text-center"> Votre liste de tâches </h2>
                    <ul class="mt-3">
                        {% for item in tasks %}
                        {% if item.status.pk != 3 %}
                        <li class="list-group-item"> <!--style="background-color:{{ item.category.color }}">-->
                            <a class="row align-items-center justify-content-center" type="submit" href="{% url 'memorize:checked' pk=item.pk %}" value="{% if item.status.pk %} Supprimer {% else %} Checked {% endif %}">
                                <div class="col-2">
                                    <img src="{{ item.category.thumbnail.url }}" alt="" class="resp">
                                </div>
                                <div class="col-9">
                                    <h3 class="task">{{ item }} <span> (ajouter le {{ item.created_on_str }}) <i class="fas fa-running"></i></span></h3>
                                    {% if item.status.title == "Effectuée" %}
                                        <p><small>Cette tache a été réalisée, cliquez dessus pour la supprimer.</small></p>
                                    {% else %}
                                        <p><small>Cette tache n'a pas encore été réalisée.</small></p>
                                    {% endif %}
                                </div>    
                                <div class="form-check form-switch col-1">
                                    <input class="form-check-input m-auto" type="checkbox" id="flexSwitch-{{item.pk}}" {% if item.status.title == "Effectuée" %} checked {% endif %}>
                                </div>
                            </a>
                        </li>   
                        {% endif %}
                        {% endfor %}
                    </ul>
                </div>
            </section>  
    {% else %}
        <section class="container m-auto">
            <h1 class="text-center m-5">Bienvenu sur Memories</h1>
            <p class="text-center mb-5">Merci de vous connecter pour profiter de nos services! <a href="{% url 'account:login' %}">Cliquez-ici.</a></p>
            <div class="w-25 text-center m-auto">
                <img src="{% static 'img/logo_rec.png' %}" alt="logo" class="img-fluid">
            </div>
        </section>
        {% endif %}
        </section>
{% endblock %}

{% block footer %}
        <script>
            document.getElementById('id_category_0').checked = true;
            document.getElementById('id_title').focus();
            document.addEventListener('click', () => {
                document.getElementById('id_title').focus();
            })
            let addSubmit = document.getElementById('submit')
            document.addEventListener("keypress", (e) => {
                if (e.keyCode === 13) {
                 e.preventDefault();
                 addSubmit.click();
                }
              });
        </script>
{% endblock %}

memorize/templates/memorize/remind-game.html
{% extends 'memorize/base.html' %}

{% block title %} Reminder!  {% endblock %}

{% block content %}
    {% include 'memorize/_flash.html' %}
    <section class="container game">
        <h1 class="text-center">{{ question }}</h1>
        <ul class="d-flex justify-content-center">
            {% for item in tasks %}
            <li class="m-2">
                <a class="btn btn-lg" href="{% url 'memorize:reminder-game-check' pk=item.pk %}">
                    {{ item.title | title }} 
                </a>
            </li>
            {% endfor %}
        </ul> 
        {% include 'memorize/_score.html' %}   
    </section>      
{% endblock %}